### ISSUE TITLE
PHP 8.3 nightly missing Unicode PCRE properties

### ISSUE THREAD

**Issue by curry684** [shivammathur/setup-php#779]
The following code does not work in PHP 8.3 nightly:
```php
var_dump(preg_match('#\\p{cyrillic}#u', 'Пример')); # Should be 1
var_dump(preg_match('#\\p{cyrillic}#u', 'Latin'));  # Should be 0
```
Even though it should: https://3v4l.org/4sRgY#v8.2.11

You can see it fail in https://github.com/omines/antispam-bundle/actions/runs/6769796730/job/18396922196:
```
1) /home/runner/work/antispam-bundle/antispam-bundle/src/Validator/Constraints/BannedScriptsValidator.php:34
preg_match(): Compilation failed: unknown property name after \P or \p at offset 13
```
8.1 and 8.2 are passing the same test suite. My local 8.3 install passes it as well.

As far as I can see this error results from the PCRE extension being built without `--enable-unicode-properties` flag. It's pretty much impossible to validate that hypothesis though as the switch is not exposed through PHP.

**Comment by curry684** [comment]
I've set up a dedicated test case, turns out the code successfully runs on 7.3 to 8.2 only.

PHP 5.6 to 7.2 and the nightlies of 8.3 and 8.4 fail.

https://github.com/curry684/regexp-actions/actions/runs/6771604589

**Comment by shivammathur** [comment]
Thanks for reporting this.

Fixed in https://github.com/shivammathur/php-builder/commit/bf0252650611d2f2ad37660da62d4613066bca48

Please restart your workflow, it should work correctly now for PHP 7.3 to 8.4

**Comment by curry684** [comment]
Yessss, thank you!

https://github.com/curry684/regexp-actions/actions/runs/6771604589

**Comment by curry684** [comment]
@shivammathur the problem returned now that 8.3 is stable  😉 

https://github.com/omines/antispam-bundle/actions/runs/7020097667/job/19099047187

**Comment by shivammathur** [comment]
@curry684 

FIxed in https://github.com/shivammathur/php-ubuntu/commit/c05854720bc765dee8fdaef650cc485b994b8cef

**Comment by curry684** [comment]
Thank you, confirmed @ https://github.com/omines/antispam-bundle/actions/runs/7026796018
