### ISSUE TITLE
Bug: Extension installation regression with PHP >= 8.4

### ISSUE THREAD

**Issue by pprkut** [shivammathur/setup-php#1076]
### Describe the bug

After the upgrade of PHP from 8.4.19 to 8.4.20 some extensions no longer install successfully. So far we encountered issues for `uopz` and `uuid`.

`uopz` fails with:
```
  /tmp/uopz-7.1.1/src/handlers.c:127:27: error: 'ZEND_EXIT' undeclared here (not in a function); did you mean 'ZEND_CAST'?
    127 |         UOPZ_HANDLER_DECL(ZEND_EXIT,                                    exit)
        |                           ^~~~~~~~~
  /tmp/uopz-7.1.1/src/handlers.c:81:42: note: in definition of macro 'UOPZ_HANDLER_DECL'
     81 | #define UOPZ_HANDLER_DECL(o, n)         {o, &zend_vm_##n, uopz_vm_##n},
```

AFAIK the `ZEND_EXIT` removal should've also impacted earlier PHP 8.4 versions, so perhaps a patch for this is no longer applied?
8.5 now fails here too, while previously the extension would at least compile correctly (even though it was not usable after)

`uuid` fails with:
```
Configuring extension
checking whether uuid is available... yes, shared
checking for the location of libuuid... configure: error: not found
```
It has the same issue on 8.5 as well

### Version

- [ ] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

ubuntu-latest

### PHP versions

PHP 8.4, PHP 8.5

### To Reproduce

```
      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: 8.4
          extensions: apcu, pecl_http, ssh2, uopz, uuid
```

### Expected behavior

Both uopz and uuid install without problems

### Are you willing to submit a PR?

Yes

**Comment by pprkut** [comment]
Not sure if you changed something or not, but it started working again for me 🙂

**Comment by shivammathur** [comment]
@pprkut 

Ubuntu servers are having issues today, so the library package earlier must have failed to download. 
It is resolved now.
https://status.canonical.com/#/incident/KNms6QK9ewuzz-7xUsPsNylV20jEt5kyKsd8A-3ptQG-0Dp5D6IWR-Dw5G2pjG-aXrj_4QfzB2lRNFJhfuReyQ==

**Comment by bmckay959** [comment]
I have started receiving an error saying the 'gd' extension is not installed. I'm curious if this could be connected to canonical being under attack? I've debugged now for 4 hours and can't think of anything else? 

I'm wondering if your issue with an extension was auto resolved? Or did you do something?

https://status.canonical.com/
